apiVersion: v1
kind: ConfigMap
metadata:
  name: rain-tracker-config
  namespace: rain-tracker
data:
  SERVER_HOST: "0.0.0.0"
  SERVER_PORT: "8080"
  GAUGE_URL: "https://alert.fcd.maricopa.gov/php/showdata4.php?ID=59700&NM=1000"
  GAUGE_LIST_URL: "https://alert.fcd.maricopa.gov/alert/Rain/ev_rain.txt"
  FETCH_INTERVAL_MINUTES: "15"
  GAUGE_LIST_INTERVAL_MINUTES: "60"
  FOPR_WORKER_CONCURRENCY: "10"
  RUST_LOG: "debug"
